version: '3.8'

services:
  backend-blue:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:blue
    container_name: backend-blue
    ports:
      - '3005:3005'
    networks:
      - app-network   # ✅ FIXED (same as green)
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    external: true   # ✅ use existing network created by green