version: '3'
services:
    backend_green:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
        image: backend:green
        container_name: backend-green
        ports:
            - '3006:3005'
        networks:
            - vaidikvivah-network
        restart: always
        env_file:
            - .env
        environment:
            - TZ=Asia/Kolkata
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s
networks:
  vaidikvivah-network:
    external: true
