version: '3'
services:
  backend:
    container_name: wedlock-backend
    build: .
    ports:
      - "3005:3005"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"  # <-- Confirm your host IP

  redis:
    image: redis:latest
    container_name: wedlock-redis
    restart: always
