name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH & Deploy
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Your deployment commands here, e.g.
            cd /home/ubuntu/app || git clone https://github.com/veredadigitaltech/wedlock-backend.git app && cd app
            git pull origin main
            docker stop api-wedlock || true
            docker rm api-wedlock || true
            docker build -t api-wedlock .
            docker run -d -p 3005:3005 --name api-wedlock api-wedlock
          EOF
